# frozen_string_literal: true

require_relative 'services/git_reader'
require_relative 'services/git_writer'
require_relative 'services/ollama_client'
require_relative 'services/diff_parser'
require_relative 'services/diff_summarization/diff_summarizer'
require_relative 'services/prompt_builder'
require_relative 'services/interactive_prompt'
require_relative 'services/pr_opener'
require_relative 'services/clipboard'
require_relative 'services/spinner'
require_relative 'flows/base_flow'
require_relative 'flows/commit_flow'
require_relative 'flows/pr_flow'
