# frozen_string_literal: true

require_relative 'services/helpers/config_loader'
require_relative 'services/git/git_reader'
require_relative 'services/git/git_writer'
require_relative 'services/ollama_client'
require_relative 'services/git/diff_parser'
require_relative 'services/diff_summarization/diff_summarizer'
require_relative 'services/helpers/prompt_builder'
require_relative 'services/helpers/interactive_prompt'
require_relative 'services/git/pr/pr_opener'
require_relative 'services/helpers/clipboard'
require_relative 'services/helpers/spinner'
require_relative 'services/flow_context_builder'
require_relative 'services/message_generator'
require_relative 'services/message_presenter'
require_relative 'services/git/commit/commit_staging'
require_relative 'services/git/commit/commit_execution'
require_relative 'flows/base_flow'
require_relative 'flows/commit_flow'
require_relative 'flows/pr_flow'
